# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 03:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import epa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_images', models.PositiveIntegerField(db_column=b'MaxImageCount')),
                ('interval', models.PositiveIntegerField(db_column=b'Days')),
                ('point', models.CharField(db_column=b'Point', max_length=200)),
            ],
            options={
                'db_table': 'AlgorithmConfiguration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataManagementTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_column=b'Url', max_length=2000)),
                ('request_date', models.DateTimeField(db_column=b'RequestDate')),
            ],
            options={
                'db_table': 'DataManagementTrigger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column=b'Subject', max_length=100)),
                ('message', models.CharField(db_column=b'Message', max_length=2000)),
                ('date_sent', models.DateTimeField(db_column=b'DateSent')),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(db_column=b'Point', max_length=200)),
            ],
            options={
                'db_table': 'PredictionPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(db_column=b'DateRequested')),
                ('date_fulFilled', models.DateTimeField(db_column=b'DateFulfilled', null=True)),
            ],
            options={
                'db_table': 'PredictionRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cell', models.IntegerField()),
                ('recent_event', models.IntegerField()),
                ('highest_level_cell', models.IntegerField()),
                ('normalized_index', models.IntegerField()),
                ('change_history_chart', models.ImageField(upload_to=b'aggregate/')),
                ('last_year_chart', models.ImageField(upload_to=b'aggregate/')),
                ('change_history_data', models.CharField(blank=True, max_length=500, null=True)),
                ('last_year_data', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_point', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epa.HelpCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionAlgorithmConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_images', models.PositiveIntegerField()),
                ('interval', models.PositiveIntegerField()),
                ('prediction_point', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('result', models.ImageField(upload_to=b'prediction/')),
                ('cells', models.FloatField()),
                ('futureDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=epa.models.OverwriteStorage(), upload_to=b'data/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=b'thumb/')),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 10, 5, 3, 23, 6, 673908))),
                ('type', models.IntegerField(choices=[(0, b'Image'), (1, b'Text')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
